### ISSUE TITLE
games-emulation/desmune Digest verification failed & keywording on live ebuilds

### ISSUE THREAD

**Issue by Kusoneko** [FlyingWaffleDev/waffle-builds#2]
Hello,
so, I'm just typing this up so that it can perhaps someday get fixed and stop complaining at every `emerge -uUD @world` I do. When doing that, I receive the following error:

```
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] games-emulation/desmume-9999::waffle-builds [0.9.11-r2::gentoo] USE="openal%* -glade% -hud% -soundtouch% -wifi%" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB

>>> Emerging (1 of 1) games-emulation/desmune-9999::waffle-builds

!!! Digest verification failed:
!!! /var/lib/layman/waffle-builds/games-emulation/desmune/metadata.xml
!!! Reason: Filesize does not match recorded size
!!! Got: 513
!!! Expected: 616
```

On the other hand, considering it's trying to update my gentoo repository's desmune, perhaps it would be better if it also was keyworded with `**` like pretty much every live ebuild is in the official gentoo repository. I also think that the same should apply to `net-im/qtox-9999` so that it stops attempting to update it when using version 1.17.3. I haven't seen any live ebuilds before this repository that keywords the live ebuilds with `~arch` instead of `**` which is apparently done by leaving the `KEYWORDS` field empty.

**Comment by FlyingWaffleDev** [comment]
Sorry it took me so long to notice and fix this!  I've mostly switched to MelonDS and was unavailable for the last few months.  Latest commit should have this fixed (I had edited the matadata.xml without updating the manifest).
