### ISSUE TITLE
protonvpn-cli dependancies

### ISSUE THREAD

**Issue by mathroc** [FlyingWaffleDev/waffle-builds#3]
I had to add a few useflags in order to make proton vpn cli work:

* net-misc/networkmanager introspection ⇒ protonvpn lib cannor communciate with NetworkManager without this one (`ValueError: Namespace NM not available` similar to https://bugs.gentoo.org/683730)

I had already nm-applet installed but I think it should be added as a dependancy, even for the protonvpn-**cli** (see https://github.com/ProtonVPN/linux-cli/issues/1 https://github.com/ProtonVPN/linux-cli/issues/35 & https://github.com/ProtonVPN/linux-cli/issues/45)

* net-vpn/networkmanager-openvpn gtk ⇒ causes the error `Failed to request VPN secrets #3: No agents were available for this request` when missing (needed for nm-applet openvpn plugin afaict)

**Comment by sjfloat** [comment]
Could this be related to the "Namespace NM not available" I'm getting with the cli?

**Comment by mathroc** [comment]
> Could this be related to the "Namespace NM not available" I'm getting with the cli?

yes it is, you need to install the `net-misc/networkmanager` package with the `introspection` use flag

**Comment by FlyingWaffleDev** [comment]
The old ProtonVPN version is deprecated (and also not functional for Python >3.10), so it has been removed. ProtonVPN's new beta GTK application has been added as a replacement.
