### ISSUE TITLE
No Manifest file on media-fonts/nerd-fonts

### ISSUE THREAD

**Issue by Plexvola** [FlyingWaffleDev/waffle-builds#4]
There is no manifest for the `media-fonts/nerd-fonts` package.

**Comment by TheMainMMan** [comment]
Indeed, simple and easy fix, I wonder why it isn't fixed for so long.

**Comment by FlyingWaffleDev** [comment]
Fixed by [20509a0](https://github.com/FlyingWaffleDev/waffle-builds/commit/20509a05fcd33277e1cdb4af453713da3a0c8868)
