### ISSUE TITLE
protonvpn-gui vs protonvpn-cli

### ISSUE THREAD

**Issue by Tara-Li** [FlyingWaffleDev/waffle-builds#6]
Jeannie ~ # emerge protonvpn-gui

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] net-vpn/protonvpn-gui-1.3.0::waffle-builds  USE="-appindicator" PYTHON_TARGETS="python3_9 -python3_8 -python3_10" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] y

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) net-vpn/protonvpn-gui-1.3.0::waffle-build
-----
* Detected file collision(s):
 * 
 * 	/usr/lib/python-exec/python3.9/protonvpn
 * 	/usr/bin/protonvpn
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * net-vpn/protonvpn-cli-2.2.11:0::gentoo
 * 	/usr/bin/protonvpn
 * 	/usr/lib/python-exec/python3.9/protonvpn
 * 
 * Package 'net-vpn/protonvpn-gui-1.3.0' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.

**Comment by FlyingWaffleDev** [comment]
The old ProtonVPN version is deprecated (and also not functional for Python >3.10), so it has been removed. ProtonVPN's new beta GTK application has been added as a replacement.
