### ISSUE TITLE
Gimp fails to build with nerd-fonts installed

### ISSUE THREAD

**Issue by kopr12** [FlyingWaffleDev/waffle-builds#9]
it can't access .uuid files, solved by running `fc-cache -fs` , adding that command to ebuild might be a good idea.

**Comment by FlyingWaffleDev** [comment]
Fixed in [56c3eb9](https://github.com/FlyingWaffleDev/waffle-builds/commit/56c3eb9ef0c4533cc5af1d2252cff7e1981eff0e)
